build: {}
dependencies:
    applications: sandiego.gov-opendsd-index-applications-received->=0.0.2
extract: {}
sources:
    approval:
        url: http://opendsd.sandiego.gov/api/approval/{id}
    code_enforcement:
        url: http://opendsd.sandiego.gov/api/codeenforcement/{id}
    project:
        url: http://opendsd.sandiego.gov/api/project/{id}
views: {}
