build:
    dependencies: {}
    name_transforms: meta/name_transforms.csv
    revised_name_transforms: meta/name_transforms_revised.csv
dependencies:
    blocks: census.gov-geography-dim-orig-blocks-ca
    schools: cde.ca.gov-schools-orig
extract: {}
partitions:
-   name: cde.ca.gov-schools-combined-public_schools
    table: public_schools
