build:
    sources:
        header_end: 0
        header_start: 0
dependencies: {}
extract: {}
sources:
    colleges:
        url: http://ds.civicknowledge.org.s3.amazonaws.com/cccco.edu/WageOutcomesCollegeSummary.csv
    summary:
        url: http://ds.civicknowledge.org.s3.amazonaws.com/cccco.edu/WageOutcomesSummary.csv
