about: {}
build:
    sources:
        sdcommunities: http://rdw.sandag.org/file_store/Community/Community_Plan_SD.zip
        sdneighborhoods: http://rdw.sandag.org/file_store/Community/Neighborhoods_SD.ZIP
identity:
    dataset: neighborhoods
    id: d00P
    revision: 1
    source: sangis.org
    variation: orig
    version: 0.1.1
names:
    fqname: sangis.org-neighborhoods-orig-0.1.1~d00P001
    name: sangis.org-neighborhoods-orig
    vid: d00P001
    vname: sangis.org-neighborhoods-orig-0.1.1
partitions:
-   format: geo
    name: sangis.org-neighborhoods-orig-sdcommunities-geo
    table: sdcommunities
-   format: geo
    name: sangis.org-neighborhoods-orig-sdneighborhoods-geo
    table: sdneighborhoods
views:
    communities:
        communities_norm: SELECT OGC_FID as id, cpname as name, AsText(geometry) as
            wkt, Area(geometry) as area FROM communities
    neighborhoods:
        neighborhoods_norm: SELECT OGC_FID as id, name, AsText(geometry) as wkt, Area(geometry)
            as area FROM neighborhoods
