build:
    header:
    - permit_no
    - type
    - received
    - approved
    - name
    - comments
    - duration
    requirements:
        xlrd: xlrd
dependencies: {}
extract: {}
sources:
    permits:
        description: Permits for downtown San Diego from Civic San Diego
        url: http://ds.civicknowledge.org.s3.amazonaws.com/civicsd.com/Development%20Permits%202004-2014%20Stats.xls
views: {}
