build:
    dependencies: {}
    fields_file: meta/fields-{}.yaml
    index_url: http://www.cde.ca.gov/ta/ac/ap/apidatafiles.asp
    requirements:
        bs4: beautifulsoup4
        dbfpy: http://downloads.sourceforge.net/project/dbfpy/dbfpy/2.2.5/dbfpy-2.2.5.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fdbfpy%2Ffiles%2F&ts=1384979899&use_mirror=hivelocity
    schema_source_file: meta/schema.yaml
    urls_file: meta/urls.yaml
dependencies: {}
extract: {}
