build:
    dependencies: {}
    private_schools:
        index: http://www.cde.ca.gov/ds/si/ps/
        source_package: private-schools-in-california
    public_schools:
        schema: http://www.cde.ca.gov/ds/si/ds/fspubschls.asp
        url: ftp://ftp.cde.ca.gov/demo/schlname/pubschls.txt
    requirements:
        ckanclient: git+https://github.com/okfn/ckanclient.git
dependencies: {}
extract: {}
