build:
    codes_file: meta/codes_{}.yaml
    datatypes_file: meta/datatypes_{}.csv
    dependencies: {}
    field_codes:
        '#': -100
        '*': -100
        4y: -200
        a: -1
        b: -2
        bad: -200
        c: -3
        d: -4
        e: -5
        es: -200
        f: -6
        h: -8
        i: -9
        m: -13
        missing: -102
        n: -14
        n/a: -101
        n/r: -101
        s: -19
        t: -20
        x: -24
        y: -25
dependencies:
    orig: cde.ca.gov-api-orig
extract: {}
extracts:
    base-csv:
        description: API Base in CSV Format
        name: cal-api-base-99-12.csv
        partition: cde.ca.gov-api-combined-429e.api_base
    base-fields:
        description: Report of the column names and descriptions in all base files,
            and what year of file each column and description appears in.
        file: meta/all_fields_by_year_base.csv
        name: columns_by_year_base.csv
    documentation:
        description: Dataset documentation
        file: meta/about.documentation.md
        name: documentation.html
    growth-csv:
        description: API Growth in CSV Format
        name: cal-api-growth-99-13.csv
        partition: cde.ca.gov-api-combined-429e.api_growth
    growth-fields:
        description: Report of the column names and descriptions in all growth files,
            and what year of file each column and description appears in.
        file: meta/all_fields_by_year_growth.csv
        name: columns_by_year_growth.csv
    schema:
        description: The schema for all tables, as a CSV file.
        file: meta/schema.csv
        name: schema.csv
partitions: []
